/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author Manuel Torres
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Vista de Consultas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consulta1_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menu_btn = new javax.swing.JButton();
        consulta2_btn = new javax.swing.JButton();
        consulta3_btn = new javax.swing.JButton();
        consulta4_btn = new javax.swing.JButton();
        consulta5_btn = new javax.swing.JButton();
        consulta6_btn = new javax.swing.JButton();
        consulta7_btn = new javax.swing.JButton();
        consulta8_btn = new javax.swing.JButton();
        consulta1_btn1 = new javax.swing.JButton();
        consulta2_btn1 = new javax.swing.JButton();
        consulta3_btn1 = new javax.swing.JButton();
        consulta4_btn1 = new javax.swing.JButton();
        consulta5_btn1 = new javax.swing.JButton();
        consulta6_btn1 = new javax.swing.JButton();
        consulta7_btn1 = new javax.swing.JButton();
        consulta8_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consulta1_btn.setText("Consulta1");
        consulta1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Consultas");

        menu_btn.setText("Menu");
        menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_btnActionPerformed(evt);
            }
        });

        consulta2_btn.setText("Consulta2");
        consulta2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta2_btnActionPerformed(evt);
            }
        });

        consulta3_btn.setText("Consulta3");
        consulta3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta3_btnActionPerformed(evt);
            }
        });

        consulta4_btn.setText("Consulta4");
        consulta4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta4_btnActionPerformed(evt);
            }
        });

        consulta5_btn.setText("Consulta5");
        consulta5_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta5_btnActionPerformed(evt);
            }
        });

        consulta6_btn.setText("Consulta6");
        consulta6_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta6_btnActionPerformed(evt);
            }
        });

        consulta7_btn.setText("Consulta7");
        consulta7_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta7_btnActionPerformed(evt);
            }
        });

        consulta8_btn.setText("Consulta8");
        consulta8_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta8_btnActionPerformed(evt);
            }
        });

        consulta1_btn1.setText("Consulta9");
        consulta1_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1_btn1ActionPerformed(evt);
            }
        });

        consulta2_btn1.setText("Consulta10");
        consulta2_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta2_btn1ActionPerformed(evt);
            }
        });

        consulta3_btn1.setText("Consulta11");
        consulta3_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta3_btn1ActionPerformed(evt);
            }
        });

        consulta4_btn1.setText("Consulta12");
        consulta4_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta4_btn1ActionPerformed(evt);
            }
        });

        consulta5_btn1.setText("Consulta13");
        consulta5_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta5_btn1ActionPerformed(evt);
            }
        });

        consulta6_btn1.setText("Consulta14");
        consulta6_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta6_btn1ActionPerformed(evt);
            }
        });

        consulta7_btn1.setText("Consulta15");
        consulta7_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta7_btn1ActionPerformed(evt);
            }
        });

        consulta8_btn1.setText("Consulta16");
        consulta8_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta8_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(menu_btn)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulta8_btn)
                    .addComponent(consulta7_btn)
                    .addComponent(consulta6_btn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(consulta4_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta3_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta1_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta2_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta5_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulta8_btn1)
                    .addComponent(consulta7_btn1)
                    .addComponent(consulta6_btn1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(consulta4_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta3_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta1_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta2_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consulta5_btn1)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(menu_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consulta1_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta2_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta3_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta4_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta5_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta6_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta7_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta8_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consulta1_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta2_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta3_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta4_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulta5_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta6_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta7_btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta8_btn1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_btnActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_btnActionPerformed

    private void consulta1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1_btnActionPerformed
        // TODO add your handling code here:
        consulta1 con = new consulta1();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta1_btnActionPerformed

    private void consulta2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta2_btnActionPerformed
        // TODO add your handling code here:
        consulta2 con = new consulta2();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta2_btnActionPerformed

    private void consulta3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta3_btnActionPerformed
        // TODO add your handling code here:
        consulta3 con = new consulta3();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta3_btnActionPerformed

    private void consulta4_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta4_btnActionPerformed
        // TODO add your handling code here:
        consulta4 con = new consulta4();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta4_btnActionPerformed

    private void consulta5_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta5_btnActionPerformed
        // TODO add your handling code here:
        consulta5 con = new consulta5();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta5_btnActionPerformed

    private void consulta7_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta7_btnActionPerformed
        // TODO add your handling code here:
        consulta7 con = new consulta7();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta7_btnActionPerformed

    private void consulta6_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta6_btnActionPerformed
        // TODO add your handling code here:
        consulta6 con= new consulta6();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta6_btnActionPerformed

    private void consulta8_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta8_btnActionPerformed
        // TODO add your handling code here:
        consulta8 con = new consulta8();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta8_btnActionPerformed

    private void consulta1_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1_btn1ActionPerformed
        // TODO add your handling code here:
                consulta1 con = new consulta1();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta1_btn1ActionPerformed

    private void consulta2_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta2_btn1ActionPerformed
                consulta2 con = new consulta2();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta2_btn1ActionPerformed

    private void consulta3_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta3_btn1ActionPerformed
                consulta3 con = new consulta3();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta3_btn1ActionPerformed

    private void consulta4_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta4_btn1ActionPerformed
            consulta4 con = new consulta4();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta4_btn1ActionPerformed

    private void consulta5_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta5_btn1ActionPerformed
            consulta5 con = new consulta5();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta5_btn1ActionPerformed

    private void consulta6_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta6_btn1ActionPerformed
              consulta6 con = new consulta6();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta6_btn1ActionPerformed

    private void consulta7_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta7_btn1ActionPerformed
           consulta7 con = new consulta7();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta7_btn1ActionPerformed

    private void consulta8_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta8_btn1ActionPerformed
         consulta8 con = new consulta8();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_consulta8_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulta1_btn;
    private javax.swing.JButton consulta1_btn1;
    private javax.swing.JButton consulta2_btn;
    private javax.swing.JButton consulta2_btn1;
    private javax.swing.JButton consulta3_btn;
    private javax.swing.JButton consulta3_btn1;
    private javax.swing.JButton consulta4_btn;
    private javax.swing.JButton consulta4_btn1;
    private javax.swing.JButton consulta5_btn;
    private javax.swing.JButton consulta5_btn1;
    private javax.swing.JButton consulta6_btn;
    private javax.swing.JButton consulta6_btn1;
    private javax.swing.JButton consulta7_btn;
    private javax.swing.JButton consulta7_btn1;
    private javax.swing.JButton consulta8_btn;
    private javax.swing.JButton consulta8_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton menu_btn;
    // End of variables declaration//GEN-END:variables
}
